apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels: 
    tier: db-tier
    app: myapp
spec:
  containers:
    - name: postgres
      image: postgres
      env: 
       - name : POSTGRES_PASSWORD 
         value: mysecretpassword